import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const ADMIN_EMAIL='suhailahmedaamro786@gmail.com';
function db(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Server Supabase configuration is missing');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})}
async function adminAuth(req:NextRequest){const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required');const admin=db();const {data,error}=await admin.auth.getUser(token);if(error||!data.user||data.user.email?.toLowerCase()!==ADMIN_EMAIL)throw new Error('Admin access required');return admin}
export async function GET(req:NextRequest){try{const admin=await adminAuth(req);const {data,error}=await admin.from('teachers').select('id,user_id,employee_id,full_name,cnic,phone,email,designation,department,joining_date,active,teacher_class_assignments(class_id,subject,is_class_teacher,classes(name,section))').order('full_name');if(error)throw error;const teachers=(data||[]).map((t:any)=>{const a=Array.isArray(t.teacher_class_assignments)?t.teacher_class_assignments[0]:t.teacher_class_assignments;const cls=Array.isArray(a?.classes)?a.classes[0]:a?.classes;return {...t,teacher_class_assignments:undefined,class_name:cls?.name?cls.name+' — '+(cls.section||''):null,subject:a?.subject||null}});return NextResponse.json({teachers})}catch(e:any){return NextResponse.json({error:e?.message||'Server error'},{status:e?.message==='Admin access required'?403:500})}}
export async function POST(req:NextRequest){try{const admin=await adminAuth(req);const b=await req.json();const required=['full_name','employee_id','email','password'];for(const k of required)if(!String(b[k]||'').trim())return NextResponse.json({error:k+' is required'},{status:400});if(String(b.password).length<8)return NextResponse.json({error:'Password must be at least 8 characters'},{status:400});if(b.cnic&&!/^\d{13}$/.test(String(b.cnic)))return NextResponse.json({error:'CNIC must be exactly 13 digits'},{status:400});if(b.phone&&!/^\d{11}$/.test(String(b.phone)))return NextResponse.json({error:'Phone must be exactly 11 digits'},{status:400});
const {data:created,error:ce}=await admin.auth.admin.createUser({email:String(b.email).trim().toLowerCase(),password:String(b.password),email_confirm:true,user_metadata:{role:'teacher',full_name:String(b.full_name).trim(),employee_id:String(b.employee_id).trim()}});if(ce)throw ce;if(!created.user)throw new Error('Teacher Auth account was not created');
const {data:teacher,error:te}=await admin.from('teachers').insert({user_id:created.user.id,employee_id:String(b.employee_id).trim(),full_name:String(b.full_name).trim(),cnic:b.cnic||null,phone:b.phone||null,email:String(b.email).trim().toLowerCase(),designation:'Teacher',department:b.department||null,active:true}).select('id').single();if(te){await admin.auth.admin.deleteUser(created.user.id);throw te}
if(b.class_id){const {error:ae}=await admin.from('teacher_class_assignments').insert({teacher_id:teacher.id,class_id:b.class_id,subject:b.subject||null,is_class_teacher:!!b.is_class_teacher,active:true});if(ae){await admin.from('teachers').delete().eq('id',teacher.id);await admin.auth.admin.deleteUser(created.user.id);throw ae}}
return NextResponse.json({ok:true,teacher_id:teacher.id})}catch(e:any){return NextResponse.json({error:e?.message||'Server error'},{status:e?.message==='Admin access required'?403:500})}}